title:              I&E Basics
email:              your-email@example.com
description:        Innovation and Entrepreneurship Basics 2019
author:             I&E Basics
baseurl:            "/IEweb"
url:                "https://davidegagliardi.com/IEweb/"

# Social Profiles
# twitter_username:   SBootstrap
# github_username:    BlackrockDigital
# facebook_username:  StartBootstrap
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           30
paginate_path:      "/lectures/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
